server:
  port: 8083
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongodb
      password: mongodb
      database: mongodb
springdoc:
  swagger-ui:
    path: /
    operationsSorter: alpha
    tagsSorter: alpha
location:
  api:
    base-url: https://open.oapi.vn/location