server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/location_service?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /
    operationsSorter: alpha
    tagsSorter: alpha
location:
  api:
    base-url: https://open.oapi.vn/location