server:
  port: 8088
springdoc:
  swagger-ui:
    path: /
    operationsSorter: alpha
    tagsSorter: alpha
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
      username: mongodb
      password: mongodb
      auto-index-creation: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      group-id: shipping-service
      properties:
        spring:
          json:
            trusted:
              packages: *