server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/foodygo?useUnicode=true&characterEncoding=UTF-8
    username: mysql
    password: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      group-id: shipping-service
springdoc:
  swagger-ui:
    path: /
    operationsSorter: alpha
    tagsSorter: alpha
api:
  service:
    order: http://localhost:8085
    location: http://localhost:8083
#logging:
#  level:
#    org.springframework: DEBUG