server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodygo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /
    operationsSorter: alpha
    tagsSorter: alpha
api:
  service:
    order: http://localhost:8085
    location: http://localhost:8083
#logging:
#  level:
#    org.springframework: DEBUG