server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3306/foodygo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /
    operationsSorter: alpha
    tagsSorter: alpha
