server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3307/foodygo?useUnicode=true&characterEncoding=UTF-8
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /
    operationsSorter: alpha
    tagsSorter: alpha
